### ISSUE TITLE
Crash after entering anything

### ISSUE THREAD

**Issue by mohcow** [Garulf/Nexusmods-Search#2]
```
Flow Launcher version: 1.16.0
OS Version: 19045.3208
IntPtr Length: 8
x64: True

Python Path: C:\Tools\FlowLauncher\app-1.16.0\UserData\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: 
Date: 07/19/2023 21:20:02
Exception:
nexusmods-search Exception: 
Websites: https://github.com/Garulf/nexusmods-search
Author: Garulf
Version: 0.2.3
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Tools\FlowLauncher\app-1.16.0\UserData\Plugins\nexusmods-search-0.2.3\run.py", line 12, in <module>
    NexusmodsSearch()
  File "C:\Tools\FlowLauncher\app-1.16.0\UserData\Plugins\nexusmods-search-0.2.3\plugin\nexusmods_search.py", line 14, in __init__
    super().__init__()
  File "C:\Tools\FlowLauncher\app-1.16.0\UserData\Plugins\nexusmods-search-0.2.3\lib\flox\__init__.py", line 107, in __init__
    super().__init__(self.api)
  File "C:\Tools\FlowLauncher\app-1.16.0\UserData\Plugins\nexusmods-search-0.2.3\lib\flox\launcher.py", line 30, in __init__
    results = request_method(*request_parameters)
  File "C:\Tools\FlowLauncher\app-1.16.0\UserData\Plugins\nexusmods-search-0.2.3\lib\flox\__init__.py", line 113, in _query
    self.query(query)
  File "C:\Tools\FlowLauncher\app-1.16.0\UserData\Plugins\nexusmods-search-0.2.3\plugin\nexusmods_search.py", line 36, in query
    api_results = self.NXAPI.search(q, game_id=game_id)
  File "C:\Tools\FlowLauncher\app-1.16.0\UserData\Plugins\nexusmods-search-0.2.3\plugin\nexus_api.py", line 47, in search
    response = self.request("get", SEARCH_URL, SEARCH_ENDPOINT, params)
  File "C:\Tools\FlowLauncher\app-1.16.0\UserData\Plugins\nexusmods-search-0.2.3\plugin\nexus_api.py", line 34, in request
    response.raise_for_status()
  File "C:\Tools\FlowLauncher\app-1.16.0\UserData\Plugins\nexusmods-search-0.2.3\lib\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 526 Server Error:  for url: https://search.nexusmods.com/mods?terms=w&game_id=0&blocked_tags=1429&blocked_tags=1073&blocked_tags=1428&blocked_tags=1040&blocked_tags=1068&include_adult=1

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Tools\FlowLauncher\app-1.16.0\UserData\Plugins\nexusmods-search-0.2.3\run.py", line 12, in <module>
    NexusmodsSearch()
  File "C:\Tools\FlowLauncher\app-1.16.0\UserData\Plugins\nexusmods-search-0.2.3\plugin\nexusmods_search.py", line 14, in __init__
    super().__init__()
  File "C:\Tools\FlowLauncher\app-1.16.0\UserData\Plugins\nexusmods-search-0.2.3\lib\flox\__init__.py", line 107, in __init__
    super().__init__(self.api)
  File "C:\Tools\FlowLauncher\app-1.16.0\UserData\Plugins\nexusmods-search-0.2.3\lib\flox\launcher.py", line 30, in __init__
    results = request_method(*request_parameters)
  File "C:\Tools\FlowLauncher\app-1.16.0\UserData\Plugins\nexusmods-search-0.2.3\lib\flox\__init__.py", line 113, in _query
    self.query(query)
  File "C:\Tools\FlowLauncher\app-1.16.0\UserData\Plugins\nexusmods-search-0.2.3\plugin\nexusmods_search.py", line 36, in query
    api_results = self.NXAPI.search(q, game_id=game_id)
  File "C:\Tools\FlowLauncher\app-1.16.0\UserData\Plugins\nexusmods-search-0.2.3\plugin\nexus_api.py", line 47, in search
    response = self.request("get", SEARCH_URL, SEARCH_ENDPOINT, params)
  File "C:\Tools\FlowLauncher\app-1.16.0\UserData\Plugins\nexusmods-search-0.2.3\plugin\nexus_api.py", line 34, in request
    response.raise_for_status()
  File "C:\Tools\FlowLauncher\app-1.16.0\UserData\Plugins\nexusmods-search-0.2.3\lib\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 526 Server Error:  for url: https://search.nexusmods.com/mods?terms=w&game_id=0&blocked_tags=1429&blocked_tags=1073&blocked_tags=1428&blocked_tags=1040&blocked_tags=1068&include_adult=1

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 291
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 296
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 311
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 193
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 839
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 813
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

[2023-07-19.txt](https://github.com/Garulf/Nexusmods-Search/files/12099409/2023-07-19.txt)

**Comment by Garulf** [comment]
Sorry it looks like nexusmods got rid of this method for searching their site. 

I have a fix very close to completion.

**Comment by mohcow** [comment]
quick
